name: deploy apim api from artifact test
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'tag of the ordermanagement api to release'
        required: true
jobs:  
  deploy:
    name: Deploy APIM api to dev environment test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    env:
      INPUT_TAG: ${{ github.event.inputs.release-tag }}   
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.INPUT_TAG }}
    - run: |
        echo git rev-parse HEAD
      
